services:
    questdb:
        build: .
        ports:
            - "${QUESTDB_PG_PORT}:8812"
            - "${QUESTDB_HTTP_PORT}:9000"
            - "${QUESTDB_INFLUX_PORT}:9009"
        volumes:
            - ./questdb-data:/var/lib/questdb
